### ISSUE TITLE
"nil can't be coerced into Fixnum" exception after producer.deliver_messages

### ISSUE THREAD

**Issue by nickmarrone** [zendesk/ruby-kafka#188]
Hello,

In my code, I am using the synchronous producer to produce a message, and then deliver it to the kafka queue. 

```
serialized_protobuf = protobuf_message.serialize_to_string
producer.produce(serialized_protobuf, topic: 'my_topic')
producer.deliver_messages
```

Although many messages succeed, some of the time `deliver_messages` will raise an error `nil can't be coerced into Fixnum`. The stack trace is

```
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/message_buffer.rb:30:in `+'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/message_buffer.rb:30:in `concat'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/produce_operation.rb:64:in `block in send_buffered_messages'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/message_buffer.rb:44:in `block (2 levels) in each'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/message_buffer.rb:43:in `each'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/message_buffer.rb:43:in `block in each'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/message_buffer.rb:42:in `each'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/message_buffer.rb:42:in `each'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/produce_operation.rb:57:in `send_buffered_messages'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/produce_operation.rb:45:in `block in execute'
/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.12/lib/active_support/notifications.rb:125:in `instrument'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/instrumenter.rb:19:in `instrument'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/produce_operation.rb:39:in `execute'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/producer.rb:297:in `block in deliver_messages_with_retries'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/producer.rb:289:in `loop'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/producer.rb:289:in `deliver_messages_with_retries'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/producer.rb:239:in `block in deliver_messages'
/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.12/lib/active_support/notifications.rb:125:in `instrument'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/instrumenter.rb:19:in `instrument'
/vendor/bundle/ruby/2.1.0/gems/ruby-kafka-0.3.7/lib/kafka/producer.rb:232:in `deliver_messages'
```

The error appears to occur in when an empty array of messages is passed to MessageBuffer#concat and it attempts to add nil bytes to @bytesize. Although fixing the symptom appears trivial, I am at a loss to explain why there are no messages to send since my code calls the produce method immediately before deliver_messages. 

Thanks

EDIT: This is using v0.3.7 of the gem.

**Comment by dasch** [comment]
Thanks for the detailed bug report, I'll investigate this.

**Comment by dasch** [comment]
@nickmarrone the issue should be fixed on the latest master – can you confirm that's the case?

**Comment by nickmarrone** [comment]
@dasch, thanks for the quick response.

Although the fix prevents this particular error, the error gets pushed to the next location:

`nil can't be coerced into Fixnum`

```
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/message_buffer.rb:57:in `-'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/message_buffer.rb:57:in `clear_messages'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/produce_operation.rb:157:in `block in handle_response'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/protocol/produce_response.rb:32:in `block (2 levels) in each_partition'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/protocol/produce_response.rb:31:in `each'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/protocol/produce_response.rb:31:in `block in each_partition'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/protocol/produce_response.rb:30:in `each'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/protocol/produce_response.rb:30:in `each_partition'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/produce_operation.rb:110:in `handle_response'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/produce_operation.rb:99:in `block in send_buffered_messages'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/produce_operation.rb:79:in `each'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/produce_operation.rb:79:in `send_buffered_messages'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/produce_operation.rb:45:in `block in execute'\"
/gems/activesupport-3.2.12/lib/active_support/notifications.rb:125:in `instrument'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/instrumenter.rb:19:in `instrument'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/produce_operation.rb:39:in `execute'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/producer.rb:297:in `block in deliver_messages_with_retries'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/producer.rb:289:in `loop'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/producer.rb:289:in `deliver_messages_with_retries'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/producer.rb:239:in `block in deliver_messages'\"
/gems/activesupport-3.2.12/lib/active_support/notifications.rb:125:in `instrument'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/instrumenter.rb:19:in `instrument'\"
/bundler/gems/ruby-kafka-eaa49ee5db69/lib/kafka/producer.rb:232:in `deliver_messages'\"
```

Via logging, I can show that that I am writing a message when the error occurs. 

My code goes something like this
```
  def time_now_ms
    (Time.now.to_f * 1000.0).round
  end

begin
  serialized_protobuf = protobuf_message.serialize_to_string
  producer.produce(serialized_protobuf, topic: 'my_topic')
  
  start_time = time_now_ms
  producer.deliver_messages
rescue => e
  log.error "ERR: #{time_now_ms - start_time} - #{serialized_protobuf.bytesize} - #{e.message}"
end
```

I have set connection, socket, and ack timeouts to many seconds. 

The logging now shows that the failure occurs in a few ms (expected, since it is not failing on the write to kafka but because it doesn't appear to have a message), the protobuf size is around 15k, and the same error message. 

It appears that the gem is not getting a message although I am confident I am writing one. 

Looking at logging from kafka, I expected to maybe find "Failed to assign partitions" or one of the other errors from producer.rb, but I do not see any. I _am_ however seeing many "Received out-of-order response id 6, was expecting 7" type errors, and disconnects from the broker. Within my data center, I am connecting to this kafka cluster via the java and go drivers with great success. Do you have any recommendations for debugging the gem or configuration settings?

Thank you

**Comment by dasch** [comment]
1) Are you using multiple threads?
2) Can you send me a link to a full log dump that replicates the behavior?

**Comment by dasch** [comment]
Also, the exception you observed should be fixed by c945b73be43a5132741418ba57262b0dff3d0945. Hopefully we can get closer to the source.

**Comment by vitaliy** [comment]
Pulled the latest from master. Still getting "TypeError: nil can't be coerced into Fixnum"
Doing some load testing here.

[GEM_ROOT]/bundler/gems/ruby-kafka-c945b73be43a/lib/kafka/message_buffer.rb:59 in -
[GEM_ROOT]/bundler/gems/ruby-kafka-c945b73be43a/lib/kafka/message_buffer.rb:59 in clear_messages
[GEM_ROOT]/bundler/gems/ruby-kafka-c945b73be43a/lib/kafka/produce_operation.rb:157 in block in handle_response

**Comment by nickmarrone** [comment]
@dasch,

Threads are causing my problem I'm pretty sure. I believe that, with two threads, something like this is happening:

```
thread-1: producer.produce
thread-2: producer.produce
thread-1: producer.deliver_messages
thread-2: producer.deliver_messages # raises error
```

I also continued to see the same error that vitaliy noted, but I need to update my code to have a separate connection to kafka in each thread before proceeding.

**Comment by dasch** [comment]
The Kafka client is not thread safe at the moment. Can you try your existing code with #191 though? That may actually provide thread safety.

Note however that the TCP connections will _not_ be shared among threads. You can instead try to use an async producer, which should be thread safe.

**Comment by nickmarrone** [comment]
I will give that a shot.

**Comment by nickmarrone** [comment]
@dasch, that branch goes back to failing on line 30 of message_buffer.rb (pre adding the 0 in from your first fix). I am working on a version that has a separate connection for each thread.

**Comment by dasch** [comment]
Yeah, the sync producer is not thread safe. The async one should be. The
branch hasn't been rebased on master, I'll do that later.

**Comment by nickmarrone** [comment]
Ah, I see. 

The async producer will not work for me because I need to be able to ACK or fail each message as they go through my data processing pipeline. FYI, our message size, even compressed, can be several hundred KB. 

Looking in more closely, I see that the async producer uses a producer under the hood. Each producer is creating its own queue and buffer. 

Similarly, the client is creating a new connection_builder, broker_pool, and cluster. 

So, I wanted to confirm -- you are saying that the producer is not thread safe. But, is there any reason it would not be thread safe if I create a separate instance of the client and the producer for each thread?

**Comment by nickmarrone** [comment]
@dasch, 

By instantiating a different kafka client for each thread, I am not getting the error anymore. I am successfully persisting data to the kafka topic without error. Thank you for your work in helping me debug this issue. Previously, we were writing to a java service that would then persist to kafka, but we have been looking into connecting directly to kafka with a ruby for a while.

**Comment by dasch** [comment]
@nickmarrone you definitely want a separate producer per thread for the semantics you're describing. With #191 merged, you can share a single client instance, though, although under the hood it doesn't make much of a difference.

Feel free to ask if you have more questions!
